"""Initial Migration.

Revision ID: 8e8dbe3a87b4
Revises: 
Create Date: 2022-06-14 14:46:44.362386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8dbe3a87b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dokter',
    sa.Column('id_dokter', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_dokter', sa.String(length=80), nullable=False),
    sa.Column('hari_kerja', sa.String(length=80), nullable=False),
    sa.Column('jam_kerja', sa.String(length=80), nullable=False),
    sa.Column('status_pemeriksaan', sa.String(length=2), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_dokter')
    )
    op.create_table('pasien',
    sa.Column('no_pasien', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_pasien', sa.String(length=80), nullable=False),
    sa.Column('alamat_pasien', sa.String(length=80), nullable=False),
    sa.Column('status_diperiksa', sa.String(length=2), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('no_pasien')
    )
    op.create_table('dokter_history',
    sa.Column('no_dokter_history', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dokter', sa.Integer(), nullable=False),
    sa.Column('nama_dokter', sa.String(length=80), nullable=False),
    sa.Column('hari_kerja', sa.String(length=80), nullable=False),
    sa.Column('jam_kerja', sa.String(length=80), nullable=False),
    sa.Column('status_pemeriksaan', sa.String(length=2), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_dokter'], ['dokter.id_dokter'], ),
    sa.PrimaryKeyConstraint('no_dokter_history')
    )
    op.create_table('pasien_history',
    sa.Column('no_pasien_history', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no_pasien', sa.Integer(), nullable=False),
    sa.Column('nama_pasien', sa.String(length=80), nullable=False),
    sa.Column('alamat_pasien', sa.String(length=80), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['no_pasien'], ['pasien.no_pasien'], ),
    sa.PrimaryKeyConstraint('no_pasien_history')
    )
    op.create_table('trans',
    sa.Column('id_trans', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dokter', sa.Integer(), nullable=False),
    sa.Column('no_pasien', sa.Integer(), nullable=False),
    sa.Column('status_bayar', sa.String(length=2), nullable=False),
    sa.Column('status_checking_dokter', sa.String(length=2), nullable=False),
    sa.Column('resep_dokter', sa.String(length=2), nullable=False),
    sa.Column('harga_bayar', sa.Integer(), nullable=False),
    sa.Column('keluhan', sa.String(length=99), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_dokter'], ['dokter.id_dokter'], ),
    sa.ForeignKeyConstraint(['no_pasien'], ['pasien.no_pasien'], ),
    sa.PrimaryKeyConstraint('id_trans')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trans')
    op.drop_table('pasien_history')
    op.drop_table('dokter_history')
    op.drop_table('pasien')
    op.drop_table('dokter')
    # ### end Alembic commands ###
